### ISSUE TITLE
Error on updating

### ISSUE THREAD

**Issue by RC-Fandom** [Kerr1291/EnemyRandomizer#36]
I was trying to update the mod and it gave a error I will leave the error here (I'm not sure what to do :P)

Scarab Version: 2.1.0.1

System.UnauthorizedAccessException: Access to the path 'C:\Users\RC\Desktop\Hollow.Knight.v1.5.78.11833\Hollow.Knight.v1.5.78.11833\Hollow Knight_Data\Managed\Mods\Disabled\Enemy Randomizer\Readme.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Abstractions.FileStreamFactory.New(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Scarab.Services.Installer.ExtractToFile(ZipArchiveEntry src, String dest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 530
   at Scarab.Services.Installer.ExtractZip(ArraySegment`1 data, String root) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 507
   at Scarab.Services.Installer.PlaceMod(ModItem mod, Boolean enable, String filename, ArraySegment`1 data) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 432
   at Scarab.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 396
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 336
   at Scarab.Models.ModItem.OnUpdate(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 184
   at Scarab.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 801

**Comment by Kerr1291** [comment]
This "System.UnauthorizedAccessException: Access to the path 'C:\Users\RC\Desktop\Hollow.Knight.v1.5.78.11833\Hollow.Knight.v1.5.78.11833\Hollow Knight_Data\Managed\Mods\Disabled\Enemy Randomizer\Readme.txt' is denied."   Usually means that some application, notepad or otherwise, has the file open and so the file is unavailable for editing by whatever is trying to update the mod. Sometimes it means the file got marked "read only" and you just need to right click on it and change it so it's not. Either way, if this is an issue with your mod installer program then I'd direct your questions to the support channel on the hk modding discord: https://discord.gg/zuCFvxqM
